/**
 * Train Travel APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { ApiResponse, RequestOptions } from '../core';
import {
  StationsResponse,
  stationsResponseSchema,
} from '../models/stationsResponse';
import { BaseController } from './baseController';
import { ProblemError } from '../errors/problemError';

export class StationsController extends BaseController {
  /**
   * Returns a list of all train stations in the system.
   *
   * @return Response from the API call
   */
  async getStations(
    requestOptions?: RequestOptions
  ): Promise<ApiResponse<StationsResponse>> {
    const req = this.createRequest('GET', '/stations');
    req.throwOn(400, ProblemError, 'Bad Request');
    req.throwOn(401, ProblemError, 'Unauthorized');
    req.throwOn(403, ProblemError, 'Forbidden');
    req.throwOn(429, ProblemError, 'Too Many Requests');
    req.throwOn(500, ProblemError, 'Internal Server Error');
    req.authenticate([{ oAuth2: true }]);
    return req.callAsJson(stationsResponseSchema, requestOptions);
  }
}
