/**
 * Train Travel APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { AuthorizationCodeAuthManager } from './authorizationCodeAuthManager';
import { HttpClientOptions } from './clientAdapter';
import { OAuthScopeEnum } from './models/oAuthScopeEnum';
import { OAuthToken } from './models/oAuthToken';

/** An interface for all configuration parameters required by the SDK. */
export interface Configuration {
  timeout: number;
  environment: Environment;
  /** @deprecated use authorizationCodeAuthCredentials field instead */
  oAuthClientId?: string;
  /** @deprecated use authorizationCodeAuthCredentials field instead */
  oAuthClientSecret?: string;
  /** @deprecated use authorizationCodeAuthCredentials field instead */
  oAuthRedirectUri?: string;
  /** @deprecated use authorizationCodeAuthCredentials field instead */
  oAuthToken?: OAuthToken;
  /** @deprecated use authorizationCodeAuthCredentials field instead */
  oAuthScopes?: OAuthScopeEnum[];
  authorizationCodeAuthCredentials?: {
    oAuthClientId: string;
    oAuthClientSecret: string;
    oAuthRedirectUri: string;
    oAuthToken?: OAuthToken;
    oAuthScopes?: OAuthScopeEnum[];
    oAuthTokenProvider?: (
      lastOAuthToken: OAuthToken | undefined,
      authManager: AuthorizationCodeAuthManager
    ) => Promise<OAuthToken>;
    oAuthOnTokenUpdate?: (token: OAuthToken) => void;
    oAuthClockSkew?: number;
  };
  httpClientOptions?: Partial<HttpClientOptions>;
  unstable_httpClientOptions?: any;
}

/** Environments available for API */
export enum Environment {
  Production = 'production',
}
