/**
 * Train Travel APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { StationsController, StationsResponse } from '../src';
import { testClient } from './testClient';
import {
  expectHeadersToMatch,
  expectMatchingWithOptions,
  makeApiCall,
} from './testHelper';

describe('StationsController', () => {
  let controller : StationsController;

  beforeAll(() => {
    controller = new StationsController(testClient);
  });

  it('should Test get-stations', async () => {
    const page = 1;

    const coordinates = '52.5200,13.4050';

    const response = await makeApiCall(
      () => controller.getStations(page, coordinates, undefined)
    );

    expect(response.statusCode).toBe(200);

    const expectedHeaders = {
      RateLimit: ['', false],
      'Content-Type': ['application/json', true],
    };

    expectHeadersToMatch(response.headers, expectedHeaders);

    const expected: StationsResponse = {
      data: [
        {
          id: 'efdbb9d1-02c2-4bc3-afb7-6788d8782b1e',
          name: 'Berlin Hauptbahnhof',
          address: 'Invalidenstraße 10557 Berlin, Germany',
          countryCode: 'DE',
          timezone: 'Europe/Berlin',
        },
        {
          id: 'b2e783e1-c824-4d63-b37a-d8d698862f1d',
          name: 'Paris Gare du Nord',
          address: '18 Rue de Dunkerque 75010 Paris, France',
          countryCode: 'FR',
          timezone: 'Europe/Paris',
        }
      ],
    };

    expect(response.result).not.toBeNull();
    expectMatchingWithOptions(
      expected,
      response.result,
      { allowExtra: true, isOrdered: false, checkValues: false }
    );
  });
});
