/**
 * Train Travel APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { TripsController, TripsResponse } from '../src';
import { testClient } from './testClient';
import {
  expectHeadersToMatch,
  expectMatchingWithOptions,
  makeApiCall,
} from './testHelper';

describe('TripsController', () => {
  let controller : TripsController;

  beforeAll(() => {
    controller = new TripsController(testClient);
  });

  it('should Test get-trips', async () => {
    const origin = 'efdbb9d1-02c2-4bc3-afb7-6788d8782b1e';

    const destination = 'b2e783e1-c824-4d63-b37a-d8d698862f1d';

    const date = '2024-02-01T09:00:00Z';

    const bicycles = false;

    const dogs = false;

    const response = await makeApiCall(
      () => controller.getTrips(origin, destination, date, bicycles, dogs)
    );

    expect(response.statusCode).toBe(200);

    const expectedHeaders = {
      RateLimit: ['', false],
      'Content-Type': ['application/json', true],
    };

    expectHeadersToMatch(response.headers, expectedHeaders);

    const expected: TripsResponse = {
      data: [
        {
          id: 'ea399ba1-6d95-433f-92d1-83f67b775594',
          origin: 'efdbb9d1-02c2-4bc3-afb7-6788d8782b1e',
          destination: 'b2e783e1-c824-4d63-b37a-d8d698862f1d',
          departureTime: '2024-02-01T10:00:00Z',
          arrivalTime: '2024-02-01T16:00:00Z',
          operator: 'Deutsche Bahn',
          price: 50,
          bicyclesAllowed: true,
          dogsAllowed: true,
        },
        {
          id: '4d67459c-af07-40bb-bb12-178dbb88e09f',
          origin: 'b2e783e1-c824-4d63-b37a-d8d698862f1d',
          destination: 'efdbb9d1-02c2-4bc3-afb7-6788d8782b1e',
          departureTime: '2024-02-01T12:00:00Z',
          arrivalTime: '2024-02-01T18:00:00Z',
          operator: 'SNCF',
          price: 50,
          bicyclesAllowed: true,
          dogsAllowed: true,
        }
      ],
      links: {
        self: 'https://api.example.com/trips?origin=efdbb9d1-02c2-4bc3-afb7-6788d8782b1e&destination=b2e783e1-c824-4d63-b37a-d8d698862f1d&date=2024-02-01',
        next: 'https://api.example.com/trips?origin=efdbb9d1-02c2-4bc3-afb7-6788d8782b1e&destination=b2e783e1-c824-4d63-b37a-d8d698862f1d&date=2024-02-01&page=2',
      },
    };

    expect(response.result).not.toBeNull();
    expectMatchingWithOptions(
      expected,
      response.result,
      { allowExtra: true, isOrdered: false, checkValues: false }
    );
  });
});
