/**
 * Train Travel APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { anyOf, Schema, validateAndMap } from '../../schema';
import { BankAccount, bankAccountSchema } from '../bankAccount';
import { Card, cardSchema } from '../card';

/** This is a container type for any-of types. */
export type BookingPaymentSource = Card | BankAccount;

export const bookingPaymentSourceSchema: Schema<BookingPaymentSource> = anyOf([
  cardSchema,
  bankAccountSchema,
]);

export namespace BookingPaymentSource {
  /**
   * Validation method to narrow down union type to Card type case.
   *
   * This is Card case.
   */
  export function isCard(value: unknown): value is Card {
    const validationResult = validateAndMap(value, cardSchema);
    return validationResult.errors === false;
  }

  /**
   * Validation method to narrow down union type to BankAccount type case.
   *
   * This is Bank Account case.
   */
  export function isBankAccount(value: unknown): value is BankAccount {
    const validationResult = validateAndMap(value, bankAccountSchema);
    return validationResult.errors === false;
  }
}
