/**
 * Train Travel APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { object, optional, Schema, string } from '../schema';
import { AccountTypeEnum, accountTypeEnumSchema } from './accountTypeEnum';
import { Object1Enum, object1EnumSchema } from './object1Enum';

/** A bank account to take payment from. Must be able to make payments in the currency specified in the payment. */
export interface BankAccount {
  object?: Object1Enum;
  name: string;
  /** The account number for the bank account, in string form. Must be a current account. */
  number: string;
  /** The sort code for the bank account, in string form. Must be a six-digit number. */
  sortCode?: string;
  /** The type of entity that holds the account. This can be either `individual` or `company`. */
  accountType: AccountTypeEnum;
  /** The name of the bank associated with the routing number. */
  bankName: string;
  /** Two-letter country code (ISO 3166-1 alpha-2). */
  country: string;
}

export const bankAccountSchema: Schema<BankAccount> = object({
  object: ['object', optional(object1EnumSchema)],
  name: ['name', string()],
  number: ['number', string()],
  sortCode: ['sort_code', optional(string())],
  accountType: ['account_type', accountTypeEnumSchema],
  bankName: ['bank_name', string()],
  country: ['country', string()],
});
