/**
 * Train Travel APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { array, lazy, object, optional, Schema } from '../schema';
import { Booking, bookingSchema } from './booking';
import { Links, linksSchema } from './links';

export interface BookingsResponse {
  /** The wrapper for a collection is an array of objects. */
  data?: Booking[];
  /** A set of hypermedia links which serve as controls for the client. */
  links?: Links;
}

export const bookingsResponseSchema: Schema<BookingsResponse> = object({
  data: ['data', optional(array(lazy(() => bookingSchema)))],
  links: ['links', optional(lazy(() => linksSchema))],
});
