/**
 * Train Travel APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { boolean, lazy, object, optional, Schema, string } from '../schema';
import { LinksSelf, linksSelfSchema } from './linksSelf';

export interface BookingsResponse1 {
  /** Unique identifier for the booking */
  id?: string;
  /** Identifier of the booked trip */
  tripId?: string;
  /** Name of the passenger */
  passengerName?: string;
  /** Indicates whether the passenger has a bicycle. */
  hasBicycle?: boolean;
  /** Indicates whether the passenger has a dog. */
  hasDog?: boolean;
  links?: LinksSelf;
}

export const bookingsResponse1Schema: Schema<BookingsResponse1> = object({
  id: ['id', optional(string())],
  tripId: ['trip_id', optional(string())],
  passengerName: ['passenger_name', optional(string())],
  hasBicycle: ['has_bicycle', optional(boolean())],
  hasDog: ['has_dog', optional(boolean())],
  links: ['links', optional(lazy(() => linksSelfSchema))],
});
