/**
 * Train Travel APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { bigint, number, object, optional, Schema, string } from '../schema';
import { ObjectEnum, objectEnumSchema } from './objectEnum';

/** A card (debit or credit) to take payment from. */
export interface Card {
  object?: ObjectEnum;
  /** Cardholder's full name as it appears on the card. */
  name: string;
  /** The card number, as a string without any separators. On read all but the last four digits will be masked for security. */
  number: string;
  /** Card security code, 3 or 4 digits usually found on the back of the card. */
  cvc: number;
  /** Two-digit number representing the card's expiration month. */
  expMonth: bigint;
  /** Four-digit number representing the card's expiration year. */
  expYear: bigint;
  addressLine1?: string;
  addressLine2?: string;
  addressCity?: string;
  addressCountry: string;
  addressPostCode?: string;
}

export const cardSchema: Schema<Card> = object({
  object: ['object', optional(objectEnumSchema)],
  name: ['name', string()],
  number: ['number', string()],
  cvc: ['cvc', number()],
  expMonth: ['exp_month', bigint()],
  expYear: ['exp_year', bigint()],
  addressLine1: ['address_line1', optional(string())],
  addressLine2: ['address_line2', optional(string())],
  addressCity: ['address_city', optional(string())],
  addressCountry: ['address_country', string()],
  addressPostCode: ['address_post_code', optional(string())],
});
