/**
 * Train Travel APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { Schema, stringEnum } from '../schema';

/**
 * Enum for CurrencyEnum
 */
export enum CurrencyEnum {
  Bam = 'bam',
  Bgn = 'bgn',
  Chf = 'chf',
  Eur = 'eur',
  Gbp = 'gbp',
  Nok = 'nok',
  Sek = 'sek',
  Try = 'try',
}

/**
 * Schema for CurrencyEnum
 */
export const currencyEnumSchema: Schema<CurrencyEnum> = stringEnum(
  CurrencyEnum
);
