/**
 * Train Travel APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { object, optional, Schema, string } from '../schema';

export interface LinksPagination {
  next?: string;
  prev?: string;
}

export const linksPaginationSchema: Schema<LinksPagination> = object({
  next: ['next', optional(string())],
  prev: ['prev', optional(string())],
});
