/**
 * Train Travel APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { object, optional, Schema, string } from '../schema';

export interface LinksSelf {
  self?: string;
}

export const linksSelfSchema: Schema<LinksSelf> = object({
  self: ['self', optional(string())],
});
