/**
 * Train Travel APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { object, optional, Schema, string } from '../schema';

export interface LinksBooking {
  booking?: string;
}

export const linksBookingSchema: Schema<LinksBooking> = object({
  booking: ['booking', optional(string())],
});
