/**
 * Train Travel APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { Schema, stringEnum } from '../schema';

/**
 * Enum for OAuthScopeEnum
 */
export enum OAuthScopeEnum {
  Read = 'read',
  Write = 'write',
}

/**
 * Schema for OAuthScopeEnum
 */
export const oAuthScopeEnumSchema: Schema<OAuthScopeEnum> = stringEnum(
  OAuthScopeEnum
);
