/**
 * Train Travel APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { Schema, stringEnum } from '../schema';

/**
 * Enum for Object1Enum
 */
export enum Object1Enum {
  BankAccount = 'bank_account',
}

/**
 * Schema for Object1Enum
 */
export const object1EnumSchema: Schema<Object1Enum> = stringEnum(Object1Enum);
