/**
 * Train Travel APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { Schema, stringEnum } from '../schema';

/**
 * Enum for ObjectEnum
 */
export enum ObjectEnum {
  Card = 'card',
}

/**
 * Schema for ObjectEnum
 */
export const objectEnumSchema: Schema<ObjectEnum> = stringEnum(ObjectEnum);
