/**
 * Train Travel APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { array, lazy, object, optional, Schema } from '../schema';
import { Station, stationSchema } from './station';

export interface StationsResponse {
  data?: Station[];
}

export const stationsResponseSchema: Schema<StationsResponse> = object({
  data: ['data', optional(array(lazy(() => stationSchema)))],
});
