/**
 * Train Travel APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { array, lazy, object, optional, Schema } from '../schema';
import { Links, linksSchema } from './links';
import { Station, stationSchema } from './station';

export interface StationsResponse {
  /** The wrapper for a collection is an array of objects. */
  data?: Station[];
  /** A set of hypermedia links which serve as controls for the client. */
  links?: Links;
}

export const stationsResponseSchema: Schema<StationsResponse> = object({
  data: ['data', optional(array(lazy(() => stationSchema)))],
  links: ['links', optional(lazy(() => linksSchema))],
});
