/**
 * Train Travel APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { object, optional, Schema, string } from '../schema';

export interface Station {
  /** Unique identifier for the station. */
  id: string;
  /** The name of the station */
  name: string;
  /** The address of the station. */
  address: string;
  /** The country code of the station. */
  countryCode: string;
  /** The timezone of the station in the [IANA Time Zone Database format](https://www.iana.org/time-zones). */
  timezone?: string;
}

export const stationSchema: Schema<Station> = object({
  id: ['id', string()],
  name: ['name', string()],
  address: ['address', string()],
  countryCode: ['country_code', string()],
  timezone: ['timezone', optional(string())],
});
