/**
 * Train Travel APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { boolean, number, object, optional, Schema, string } from '../schema';

export interface Trip {
  /** Unique identifier for the trip */
  id?: string;
  /** The starting station of the trip */
  origin?: string;
  /** The destination station of the trip */
  destination?: string;
  /** The date and time when the trip departs */
  departureTime?: string;
  /** The date and time when the trip arrives */
  arrivalTime?: string;
  /** The name of the operator of the trip */
  operator?: string;
  /** The cost of the trip */
  price?: number;
  /** Indicates whether bicycles are allowed on the trip */
  bicyclesAllowed?: boolean;
  /** Indicates whether dogs are allowed on the trip */
  dogsAllowed?: boolean;
}

export const tripSchema: Schema<Trip> = object({
  id: ['id', optional(string())],
  origin: ['origin', optional(string())],
  destination: ['destination', optional(string())],
  departureTime: ['departure_time', optional(string())],
  arrivalTime: ['arrival_time', optional(string())],
  operator: ['operator', optional(string())],
  price: ['price', optional(number())],
  bicyclesAllowed: ['bicycles_allowed', optional(boolean())],
  dogsAllowed: ['dogs_allowed', optional(boolean())],
});
