/**
 * Train Travel APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { array, lazy, object, optional, Schema } from '../schema';
import { Links, linksSchema } from './links';
import { Trip, tripSchema } from './trip';

export interface TripsResponse {
  /** The wrapper for a collection is an array of objects. */
  data?: Trip[];
  /** A set of hypermedia links which serve as controls for the client. */
  links?: Links;
}

export const tripsResponseSchema: Schema<TripsResponse> = object({
  data: ['data', optional(array(lazy(() => tripSchema)))],
  links: ['links', optional(lazy(() => linksSchema))],
});
