/**
 * Train Travel APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { array, object, optional, Schema, unknown } from '../schema';

/** This is a generic request/response wrapper which contains both data and links which serve as hypermedia controls (HATEOAS). */
export interface WrapperCollection {
  /** The wrapper for a collection is an array of objects. */
  data?: unknown[];
  /** A set of hypermedia links which serve as controls for the client. */
  links?: unknown;
}

export const wrapperCollectionSchema: Schema<WrapperCollection> = object({
  data: ['data', optional(array(unknown()))],
  links: ['links', optional(unknown())],
});
